export default {
    FETCH_APPOINTMENT_BEGIN: 'FETCH_APPOINTMENT_BEGIN',
    FETCH_APPOINTMENT_SUCCESS: 'FETCH_APPOINTMENT_SUCCESS',
    FETCH_APPOINTMENT_ERROR: 'FETCH_APPOINTMENT_ERROR',

    DELETE_APPOINTMENT_BEGIN: 'DELETE_APPOINTMENT_BEGIN',
    DELETE_APPOINTMENT_SUCCESS: 'DELETE_APPOINTMENT_SUCCESS',
    DELETE_APPOINTMENT_ERROR: 'DELETE_APPOINTMENT_ERROR',
};
