export default {
    FECTH_EVENTS_BEGIN: 'FETCH_EVENTS_BEGIN',
    FECTH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FECTH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',

    DELETE_EVENT_BEGIN: 'DELETE_EVENT_BEGIN',
    DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
    DELETE_EVENT_ERROR: 'DELETE_EVENT_ERROR',

    CLEAR_ERROR: 'CLEAR_ERROR',
};
