export default {
    ADD_APPOINTMENT_BEGIN: 'ADD_APPOINTMENT_BEGIN',
    ADD_APPOINTMENT_SUCCESS: 'ADD_APPOINTMENT_SUCCESS',
    ADD_APPOINTMENT_ERROR: 'ADD_APPOINTMENT_ERROR',

    FETCH_APPOINTMENT_BEGIN: 'FETCH_APPOINTMENT_BEGIN',
    FETCH_APPOINTMENT_SUCCESS: 'FETCH_APPOINTMENT_SUCCESS',
    FETCH_APPOINTMENT_ERROR: 'FETCH_APPOINTMENT_ERROR',

    UPDATE_APPOINTMENT_BEGIN: 'UPDATE_APPOINTMENT_BEGIN',
    UPDATE_APPOINTMENT_SUCCESS: 'UPDATE_APPOINTMENT_SUCCESS',
    UPDATE_APPOINTMENT_ERROR: 'UPDATE_APPOINTMENT_ERROR',

    CLEAR_APPOINTMENT: 'CLEAR_APPOINTMENT',
};
